name: SQL Insert Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  run-sql:
    runs-on: self-hosted
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Insert Data into SQL Server
        run: |
          sqlcmd -S dev-clus15-lsn1.national.core.bbc.co.uk -U ALLOCATE-D -P ALLOCATE-D1 -d BBCSchedules_WP -Q "INSERT INTO DevOps_1 (Test) VALUES ('HelloJaya')"
 
      - name: Verify Data
        run: |
          sqlcmd -S dev-clus15-lsn1.national.core.bbc.co.uk -U ALLOCATE-D -P ALLOCATE-D1 -d BBCSchedules_WP -Q "SELECT * FROM DevOps_1"
